var craft_data = [
{'id': 0, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': []},
{'id': 1, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 2, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 3, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 4, 'mode': '連鎖龍紋', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '回血', ]},
{'id': 5, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '回血', ]},
{'id': 6, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '回血', ]},
{'id': 7, 'mode': '轉動龍印', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '回血', ]},
{'id': 8, 'mode': '破碎龍咒', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '回血', ]},
{'id': 9, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', ]},
{'id': 10, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '消除心符石', 'skill': ['增傷', '無視拼圖盾', ]},
{'id': 11, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '無視五屬盾', ]},
{'id': 12, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '消除心符石', 'skill': ['增傷', '無視攻前盾', ]},
{'id': 13, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '受到攻擊', 'skill': ['增傷', '增回', '減CD', ]},
{'id': 14, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', ]},
{'id': 15, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '回血', ]},
{'id': 16, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '回血', ]},
{'id': 17, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '受到攻擊', 'skill': ['增傷', ]},
{'id': 18, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '人類', 'star': '2', 'charge': '發動攻擊', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 19, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '獸類', 'star': '2', 'charge': '發動攻擊', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 20, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '神族', 'star': '2', 'charge': '4 Combo以上', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 21, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '龍類', 'star': '2', 'charge': '受到攻擊', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 22, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '妖精類', 'star': '2', 'charge': '消除心符石', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 23, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '魔族', 'star': '2', 'charge': '4 Combo以上', 'skill': ['直傷', '全體直傷', '減傷', ]},
{'id': 24, 'mode': '轉動龍印', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '增回', '無視屬性相剋', ]},
{'id': 25, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '增回', '無視屬性相剋', ]},
{'id': 26, 'mode': '破碎龍咒', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '增回', '無視屬性相剋', ]},
{'id': 27, 'mode': '轉動龍印', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '增回', '我方傷害吸收', ]},
{'id': 28, 'mode': '破碎龍咒', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '增回', '我方傷害吸收', ]},
{'id': 29, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '人類', 'star': '2', 'charge': '消除心符石', 'skill': ['增傷', '減傷', ]},
{'id': 30, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '獸類', 'star': '2', 'charge': '受到攻擊', 'skill': ['增傷', '回血', ]},
{'id': 31, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': ['增傷', '回血', ]},
{'id': 32, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '龍類', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', ]},
{'id': 33, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '妖精類', 'star': '2', 'charge': '消除心符石', 'skill': ['增傷', '回血', ]},
{'id': 34, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '魔族', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '減傷', ]},
{'id': 35, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除心符石', 'skill': ['增傷', ]},
{'id': 36, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '人類', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '單體轉全體', ]},
{'id': 37, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '獸類', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '單體轉全體', ]},
{'id': 38, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '神族', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '單體轉全體', ]},
{'id': 39, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '龍類', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '單體轉全體', ]},
{'id': 40, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '妖精類', 'star': '2', 'charge': '受到攻擊', 'skill': ['增傷', '單體轉全體', ]},
{'id': 41, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '魔族', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '單體轉全體', ]},
{'id': 42, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '延遲', ]},
{'id': 43, 'mode': '映照龍符', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '延遲', ]},
{'id': 44, 'mode': '轉動龍印', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '延遲', ]},
{'id': 45, 'mode': '映照龍符', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '延遲', ]},
{'id': 46, 'mode': '轉動龍印', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '延遲', ]},
{'id': 47, 'mode': '轉動龍印', 'attribute': '水', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '無視五屬盾', ]},
{'id': 48, 'mode': '破碎龍咒', 'attribute': '火', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '無視拼圖盾', ]},
{'id': 49, 'mode': '映照龍符', 'attribute': '木', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '無視攻前盾', ]},
{'id': 50, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '回血', ]},
{'id': 51, 'mode': '映照龍符', 'attribute': '暗', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', ]},
{'id': 52, 'mode': '破碎龍咒', 'attribute': '水', 'race': '神族', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 53, 'mode': '映照龍符', 'attribute': '火', 'race': '神族', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 54, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '神族', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 55, 'mode': '映照龍符', 'attribute': '光', 'race': '神族', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '減傷', '減CD', ]},
{'id': 56, 'mode': '轉動龍印', 'attribute': '暗', 'race': '神族', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '減傷', '減CD', ]},
{'id': 57, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 58, 'mode': '疾速龍玉', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 59, 'mode': '疾速龍玉', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '增回', '對水增傷', ]},
{'id': 60, 'mode': '疾速龍玉', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '增回', '對火增傷', ]},
{'id': 61, 'mode': '疾速龍玉', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '增回', '對木增傷', ]},
{'id': 62, 'mode': '疾速龍玉', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '增回', '對光增傷', ]},
{'id': 63, 'mode': '疾速龍玉', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '增回', '對暗增傷', ]},
{'id': 64, 'mode': '疾速龍玉', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '減CD', ]},
{'id': 65, 'mode': '破碎龍咒', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '增回', ]},
{'id': 66, 'mode': '轉動龍印', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '增回', ]},
{'id': 67, 'mode': '映照龍符', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '增回', ]},
{'id': 68, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '增回', ]},
{'id': 69, 'mode': '轉動龍印', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '增回', ]},
{'id': 70, 'mode': '連鎖龍紋', 'attribute': '水', 'race': '神族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', ]},
{'id': 71, 'mode': '破碎龍咒', 'attribute': '木', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 72, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 73, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '無視攻前盾', ]},
{'id': 74, 'mode': '轉動龍印', 'attribute': '火', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '我方傷害吸收', ]},
{'id': 75, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 76, 'mode': '裂空龍刃', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '無視屬性相剋', ]},
{'id': 77, 'mode': '裂空龍刃', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '無視屬性相剋', ]},
{'id': 78, 'mode': '裂空龍刃', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '無視屬性相剋', ]},
{'id': 79, 'mode': '裂空龍刃', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '無視屬性相剋', ]},
{'id': 80, 'mode': '裂空龍刃', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '無視屬性相剋', ]},
{'id': 81, 'mode': '裂空龍刃', 'attribute': '水', 'race': '魔族', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '減傷', '回血', ]},
{'id': 82, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除心符石', 'skill': ['符石轉心', '增回', '減CD', ]},
{'id': 83, 'mode': '裂空龍刃', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '回血', ]},
{'id': 84, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', ]},
{'id': 85, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['回血', '破防', ]},
{'id': 86, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['回血', '破防', ]},
{'id': 87, 'mode': '轉動龍印', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['回血', '破防', ]},
{'id': 88, 'mode': '映照龍符', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['回血', '破防', ]},
{'id': 89, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['回血', '破防', ]},
{'id': 90, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '消除心符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 91, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '直傷', '全體直傷', '回血', '無視屬性相剋', ]},
{'id': 92, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '神族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 93, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '意志', ]},
{'id': 94, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '減傷', ]},
{'id': 95, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 96, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['符石轉心', '迴避', ]},
{'id': 97, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['符石轉心', '迴避', ]},
{'id': 98, 'mode': '破碎龍咒', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['符石轉心', '迴避', ]},
{'id': 99, 'mode': '轉動龍印', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['符石轉心', '迴避', ]},
{'id': 100, 'mode': '轉動龍印', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['符石轉心', '迴避', ]},
{'id': 101, 'mode': '映照龍符', 'attribute': '火', 'race': '神族', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '增回', '無視五屬盾', ]},
{'id': 102, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '無視屬性相剋', ]},
{'id': 103, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 104, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '魔族', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 105, 'mode': '映照龍符', 'attribute': '暗', 'race': '魔族', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 106, 'mode': '轉動龍印', 'attribute': '木', 'race': '龍類', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '直傷', '全體直傷', '回血', ]},
{'id': 107, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '無視攻前盾', ]},
{'id': 108, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '減傷', '無視拼圖盾', ]},
{'id': 109, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '意志', '無視屬性相剋', ]},
{'id': 110, 'mode': '疾速龍玉', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['直行轉心', '增傷', '增回', ]},
{'id': 111, 'mode': '疾速龍玉', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 112, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 113, 'mode': '落影龍璃', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '延遲', ]},
{'id': 114, 'mode': '落影龍璃', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '延遲', ]},
{'id': 115, 'mode': '落影龍璃', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '延遲', ]},
{'id': 116, 'mode': '落影龍璃', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '延遲', ]},
{'id': 117, 'mode': '落影龍璃', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '延遲', ]},
{'id': 118, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '減CD', ]},
{'id': 119, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石轉心', '增傷', '回血', ]},
{'id': 120, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '增回', '減傷', ]},
{'id': 121, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 122, 'mode': '破碎龍咒', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '無視屬性相剋', '無視拼圖盾', ]},
{'id': 123, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '延遲', ]},
{'id': 124, 'mode': '落影龍璃', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '回血', '無視屬性相剋', ]},
{'id': 125, 'mode': '映照龍符', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '回血', '無視屬性相剋', ]},
{'id': 126, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['符石轉光', '回血', '延遲', ]},
{'id': 127, 'mode': '落影龍璃', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '單體轉全體', '無視拼圖盾', ]},
{'id': 128, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石強化', '增傷', '減CD', ]},
{'id': 129, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石強化', '增傷', '減CD', ]},
{'id': 130, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', '無視屬性相剋', ]},
{'id': 131, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '減CD', '破防', ]},
{'id': 132, 'mode': '落影龍璃', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['火屬追打', '增傷', '回血', ]},
{'id': 133, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除心符石', 'skill': ['符石轉心', '增回', '直傷', '單體破防直傷', ]},
{'id': 134, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減傷', ]},
{'id': 135, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '減CD', '破防', ]},
{'id': 136, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '意志', '無視屬性相剋', '無視拼圖盾', ]},
{'id': 137, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉心', '增傷', '無視攻前盾', ]},
{'id': 138, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '人類', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '直傷', '單體破防直傷', '減傷', ]},
{'id': 139, 'mode': '映照龍符', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['直行轉木', '增傷', '增回', '無視五屬盾', ]},
{'id': 140, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '魔族', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '無視攻前盾', ]},
{'id': 141, 'mode': '落影龍璃', 'attribute': '木', 'race': '魔族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 142, 'mode': '落影龍璃', 'attribute': '光', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 143, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '延遲', '無視屬性相剋', ]},
{'id': 144, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['直行轉心', '減傷', '回血', ]},
{'id': 145, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '魔族', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '反擊', '無視拼圖盾', ]},
{'id': 146, 'mode': '破碎龍咒', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['直行轉暗', '增傷', '無視五屬盾', ]},
{'id': 147, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '我方傷害吸收', '延遲', '無視屬性相剋', ]},
{'id': 148, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 149, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '回血', '減CD', ]},
{'id': 150, 'mode': '破碎龍咒', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['直行轉水', '增傷', '無視屬性相剋', ]},
{'id': 151, 'mode': '落影龍璃', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['直行轉火', '增傷', '無視屬性相剋', ]},
{'id': 152, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 153, 'mode': '轉動龍印', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['直行轉光', '增傷', '迴避', ]},
{'id': 154, 'mode': '映照龍符', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '減CD', '迴避', ]},
{'id': 155, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '增回', '延遲', ]},
{'id': 156, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減傷', '減CD', ]},
{'id': 157, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉火', '增傷', '意志', ]},
{'id': 158, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除符石', 'skill': ['增回', '減CD', '破防', ]},
{'id': 159, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', '破防', ]},
{'id': 160, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉木', '增傷', '無視五屬盾', ]},
{'id': 161, 'mode': '破碎龍咒', 'attribute': '火', 'race': '人類', 'star': '3', 'charge': '消除火符石', 'skill': ['直行轉火', '增傷', '回血', ]},
{'id': 162, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '增回', '無視屬性相剋', ]},
{'id': 163, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石轉暗', '減CD', '無視五屬盾', ]},
{'id': 164, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '意志', '破防', ]},
{'id': 165, 'mode': '落影龍璃', 'attribute': '木', 'race': '神族', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '減CD', '無視五屬盾', ]},
{'id': 166, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉光', '增傷', '減CD', ]},
{'id': 167, 'mode': '轉動龍印', 'attribute': '光', 'race': '龍類', 'star': '3', 'charge': '受到攻擊', 'skill': ['直行轉光', '增傷', '減CD', ]},
{'id': 168, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 169, 'mode': '映照龍符', 'attribute': '暗', 'race': '妖精類', 'star': '3', 'charge': '消除心符石', 'skill': ['符石轉心', '增傷', '減傷', ]},
{'id': 170, 'mode': '連鎖龍紋', 'attribute': '水', 'race': '獸類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '迴避', '無視拼圖盾', ]},
{'id': 171, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 172, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '發動攻擊', 'skill': ['增傷', '減傷', ]},
{'id': 173, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '消除符石', 'skill': ['增傷', '增回', ]},
{'id': 174, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', ]},
{'id': 175, 'mode': '擴散龍結', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['符石轉水', '增傷', '無視拼圖盾', ]},
{'id': 176, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '', 'skill': ['增傷', '直傷', '全體直傷', ]},
{'id': 177, 'mode': '擴散龍結', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['符石轉光', '增傷', '無視五屬盾', ]},
{'id': 178, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '', 'skill': ['增傷', '減CD', '無視攻前盾', ]},
{'id': 179, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '發動攻擊', 'skill': ['增傷', '增回', ]},
{'id': 180, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '4 Combo以上', 'skill': ['增傷', ]},
{'id': 181, 'mode': '裂空龍刃', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '減CD', ]},
{'id': 182, 'mode': '裂空龍刃', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '減CD', ]},
{'id': 183, 'mode': '裂空龍刃', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '減CD', ]},
{'id': 184, 'mode': '裂空龍刃', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['符石轉暗', '增傷', '無視五屬盾', ]},
{'id': 185, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '意志', '無視屬性相剋', ]},
{'id': 186, 'mode': '裂空龍刃', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['直行轉光', '減CD', '延遲', ]},
{'id': 187, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['直行轉木', '增傷', '減CD', ]},
{'id': 188, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 189, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '消除符石', 'skill': ['直行轉火', '減傷', '減CD', ]},
{'id': 190, 'mode': '裂空龍刃', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉水', '增傷', '無視攻前盾', ]},
{'id': 191, 'mode': '轉動龍印', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['符石轉水', '增傷', '減CD', ]},
{'id': 192, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['直行轉水', '無視屬性相剋', '無視五屬盾', ]},
{'id': 193, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['符石轉火', '增傷', '減CD', ]},
{'id': 194, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['直行轉火', '意志', '減CD', ]},
{'id': 195, 'mode': '落影龍璃', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['符石轉木', '增傷', '減CD', ]},
{'id': 196, 'mode': '映照龍符', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '受到攻擊', 'skill': ['直行轉木', '破防', '無視攻前盾', ]},
{'id': 197, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['符石轉光', '增傷', '減CD', ]},
{'id': 198, 'mode': '落影龍璃', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['直行轉光', '回血', '延遲', ]},
{'id': 199, 'mode': '轉動龍印', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除心符石', 'skill': ['符石轉暗', '增傷', '減CD', ]},
{'id': 200, 'mode': '映照龍符', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['直行轉暗', '直傷', '單體破防直傷', '延遲', ]},
{'id': 201, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '人類', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '減CD', '無視五屬盾', ]},
{'id': 202, 'mode': '轉動龍印', 'attribute': '暗', 'race': '獸類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 203, 'mode': '破碎龍咒', 'attribute': '水', 'race': '妖精類', 'star': '3', 'charge': '消除水符石', 'skill': ['符石轉水', '增傷', '意志', ]},
{'id': 204, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '龍類', 'star': '3', 'charge': '消除暗符石', 'skill': ['符石轉暗', '增傷', '無視五屬盾', ]},
{'id': 205, 'mode': '映照龍符', 'attribute': '光', 'race': '神族', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '減CD', '無視拼圖盾', ]},
{'id': 206, 'mode': '轉動龍印', 'attribute': '木', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['直行轉木', '增傷', '無視屬性相剋', ]},
{'id': 207, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', '無視五屬盾', ]},
{'id': 208, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', '無視拼圖盾', ]},
{'id': 209, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '受到攻擊', 'skill': ['增傷', '減CD', '無視攻前盾', ]},
{'id': 210, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉心', '減CD', '延遲', ]},
{'id': 211, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除符石', 'skill': ['直行轉心', '增傷', '無視屬性相剋', ]},
{'id': 212, 'mode': '連鎖龍紋', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '直傷', '單體破防直傷', '意志', ]},
{'id': 213, 'mode': '轉動龍印', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['符石轉水', '增傷', '增回', ]},
{'id': 214, 'mode': '破碎龍咒', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉水', '減傷', '減CD', ]},
{'id': 215, 'mode': '映照龍符', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '直傷', '全體直傷', '延遲', ]},
{'id': 216, 'mode': '落影龍璃', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['我方傷害吸收', '破防', '無視屬性相剋', ]},
{'id': 217, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['我方傷害吸收', '破防', '無視屬性相剋', ]},
{'id': 218, 'mode': '轉動龍印', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '直傷', '單體破防直傷', '意志', ]},
{'id': 219, 'mode': '破碎龍咒', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉火', '增傷', '增回', ]},
{'id': 220, 'mode': '映照龍符', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石轉火', '減傷', '減CD', ]},
{'id': 221, 'mode': '落影龍璃', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '直傷', '全體直傷', '延遲', ]},
{'id': 222, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '直傷', '全體直傷', '延遲', ]},
{'id': 223, 'mode': '轉動龍印', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['我方傷害吸收', '破防', '無視屬性相剋', ]},
{'id': 224, 'mode': '破碎龍咒', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '直傷', '單體破防直傷', '意志', ]},
{'id': 225, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': ['符石轉木', '增傷', '增回', ]},
{'id': 226, 'mode': '落影龍璃', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉木', '減傷', '減CD', ]},
{'id': 227, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉光', '減傷', '減CD', ]},
{'id': 228, 'mode': '轉動龍印', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '直傷', '全體直傷', '延遲', ]},
{'id': 229, 'mode': '破碎龍咒', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['我方傷害吸收', '破防', '無視屬性相剋', ]},
{'id': 230, 'mode': '映照龍符', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '直傷', '單體破防直傷', '意志', ]},
{'id': 231, 'mode': '落影龍璃', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉光', '增傷', '增回', ]},
{'id': 232, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['符石轉暗', '增傷', '增回', ]},
{'id': 233, 'mode': '轉動龍印', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['符石轉暗', '減傷', '回血', ]},
{'id': 234, 'mode': '破碎龍咒', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '直傷', '全體直傷', '延遲', ]},
{'id': 235, 'mode': '映照龍符', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': ['我方傷害吸收', '破防', '無視屬性相剋', ]},
{'id': 236, 'mode': '落影龍璃', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '直傷', '單體破防直傷', '意志', ]},
{'id': 237, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '發動攻擊', 'skill': ['增傷', ]},
{'id': 238, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '延遲', ]},
{'id': 239, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '2', 'charge': '4 Combo以上', 'skill': ['增傷', '延遲', ]},
{'id': 240, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '減CD', '延遲', ]},
{'id': 241, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', '無視攻前盾', ]},
{'id': 242, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', '無視五屬盾', ]},
{'id': 243, 'mode': '落影龍璃', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '減CD', '無視拼圖盾', ]},
{'id': 244, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 245, 'mode': '擴散龍結', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 246, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '1', 'charge': '消除符石', 'skill': ['增傷', ]},
{'id': 247, 'mode': '鏡像龍丸', 'attribute': '水', 'race': '沒有限制', 'star': '2', 'charge': '消除水符石', 'skill': ['增傷', '增回', ]},
{'id': 248, 'mode': '鏡像龍丸', 'attribute': '火', 'race': '沒有限制', 'star': '2', 'charge': '消除火符石', 'skill': ['增傷', '增回', ]},
{'id': 249, 'mode': '鏡像龍丸', 'attribute': '木', 'race': '沒有限制', 'star': '2', 'charge': '消除木符石', 'skill': ['增傷', '增回', ]},
{'id': 250, 'mode': '鏡像龍丸', 'attribute': '光', 'race': '沒有限制', 'star': '2', 'charge': '消除光符石', 'skill': ['增傷', '增回', ]},
{'id': 251, 'mode': '鏡像龍丸', 'attribute': '暗', 'race': '沒有限制', 'star': '2', 'charge': '消除暗符石', 'skill': ['增傷', '增回', ]},
{'id': 252, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '延遲', ]},
{'id': 253, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': ['增傷', '增回', '直傷', '全體直傷', ]},
{'id': 254, 'mode': '鏡像龍丸', 'attribute': '水', 'race': '沒有限制', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 255, 'mode': '鏡像龍丸', 'attribute': '火', 'race': '沒有限制', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 256, 'mode': '鏡像龍丸', 'attribute': '木', 'race': '沒有限制', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 257, 'mode': '鏡像龍丸', 'attribute': '光', 'race': '沒有限制', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 258, 'mode': '鏡像龍丸', 'attribute': '暗', 'race': '沒有限制', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 259, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '神族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '直傷', '全體直傷', '減CD', ]},
{'id': 260, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '魔族', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 261, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '人類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', '延遲', ]},
{'id': 262, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '獸類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '我方傷害吸收', '減CD', ]},
{'id': 263, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '龍類', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 264, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '妖精類', 'star': '3', 'charge': '消除符石', 'skill': ['增傷', '減CD', '無視五屬盾', ]},
{'id': 265, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '機械族', 'star': '3', 'charge': '發動攻擊', 'skill': ['增傷', '減CD', '無視拼圖盾', ]},
{'id': 266, 'mode': '鏡像龍丸', 'attribute': '火', 'race': '機械族', 'star': '3', 'charge': '發動攻擊', 'skill': ['符石轉火', '增傷', '減CD', ]},
{'id': 267, 'mode': '鏡像龍丸', 'attribute': '木', 'race': '機械族', 'star': '3', 'charge': '發動攻擊', 'skill': ['直行轉木', '增傷', '破防', ]},
{'id': 268, 'mode': '連鎖龍紋', 'attribute': '水', 'race': '魔族', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '減CD', '無視屬性相剋', ]},
{'id': 269, 'mode': '破碎龍咒', 'attribute': '水', 'race': '人類', 'star': '3', 'charge': '消除水符石', 'skill': ['符石轉水', '增傷', '回血', ]},
{'id': 270, 'mode': '轉動龍印', 'attribute': '水', 'race': '神族', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '直傷', '單體破防直傷', '無視五屬盾', ]},
{'id': 271, 'mode': '映照龍符', 'attribute': '水', 'race': '妖精類', 'star': '3', 'charge': '消除水符石', 'skill': ['增傷', '減CD', '迴避', ]},
{'id': 272, 'mode': '連鎖龍紋', 'attribute': '火', 'race': '妖精類', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '延遲', '無視屬性相剋', ]},
{'id': 273, 'mode': '破碎龍咒', 'attribute': '火', 'race': '龍類', 'star': '3', 'charge': '消除火符石', 'skill': ['增傷', '回血', '減CD', ]},
{'id': 274, 'mode': '落影龍璃', 'attribute': '火', 'race': '獸類', 'star': '3', 'charge': '消除火符石', 'skill': ['符石轉火', '增傷', '減CD', ]},
{'id': 275, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '獸類', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '直傷', '單體破防直傷', '無視五屬盾', ]},
{'id': 276, 'mode': '連鎖龍紋', 'attribute': '木', 'race': '神族', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '意志', '減CD', ]},
{'id': 277, 'mode': '轉動龍印', 'attribute': '木', 'race': '人類', 'star': '3', 'charge': '消除木符石', 'skill': ['增傷', '我方傷害吸收', '無視屬性相剋', ]},
{'id': 278, 'mode': '映照龍符', 'attribute': '木', 'race': '妖精類', 'star': '3', 'charge': '消除木符石', 'skill': ['直行轉木', '增傷', '減CD', ]},
{'id': 279, 'mode': '連鎖龍紋', 'attribute': '光', 'race': '龍類', 'star': '3', 'charge': '消除光符石', 'skill': ['直行轉光', '增傷', '減CD', ]},
{'id': 280, 'mode': '破碎龍咒', 'attribute': '光', 'race': '獸類', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '回血', '破防', ]},
{'id': 281, 'mode': '落影龍璃', 'attribute': '光', 'race': '魔族', 'star': '3', 'charge': '消除光符石', 'skill': ['符石轉光', '增傷', '無視攻前盾', ]},
{'id': 282, 'mode': '映照龍符', 'attribute': '光', 'race': '人類', 'star': '3', 'charge': '消除光符石', 'skill': ['增傷', '直傷', '單體破防直傷', '減CD', ]},
{'id': 283, 'mode': '連鎖龍紋', 'attribute': '暗', 'race': '妖精類', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '減CD', '迴避', ]},
{'id': 284, 'mode': '破碎龍咒', 'attribute': '暗', 'race': '神族', 'star': '3', 'charge': '消除暗符石', 'skill': ['符石轉暗', '增傷', '無視五屬盾', ]},
{'id': 285, 'mode': '轉動龍印', 'attribute': '暗', 'race': '龍類', 'star': '3', 'charge': '消除暗符石', 'skill': ['增傷', '減傷', '延遲', ]},
{'id': 286, 'mode': '落影龍璃', 'attribute': '暗', 'race': '獸類', 'star': '3', 'charge': '消除暗符石', 'skill': ['直行轉暗', '增傷', '減CD', ]},
{'id': 287, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 288, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 289, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 290, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 291, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 292, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '消除符石', 'skill': []},
{'id': 293, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 294, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 295, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 296, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 297, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 298, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '發動攻擊', 'skill': []},
{'id': 299, 'mode': '連鎖龍紋', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 300, 'mode': '破碎龍咒', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 301, 'mode': '轉動龍印', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 302, 'mode': '映照龍符', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 303, 'mode': '裂空龍刃', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 304, 'mode': '鏡像龍丸', 'attribute': '沒有限制', 'race': '沒有限制', 'star': '3', 'charge': '4 Combo以上', 'skill': []},
{'id': 305, 'mode': '落影龍璃', 'attribute': '光', 'race': '人類', 'star': '3', 'charge': '消除光符石', 'skill': []},
{'id': 306, 'mode': '鏡像龍丸', 'attribute': '暗', 'race': '人類', 'star': '3', 'charge': '消除暗符石', 'skill': []},
{'id': 307, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': []},
{'id': 308, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': []},
{'id': 309, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': []},
{'id': 310, 'mode': '', 'attribute': '', 'race': '', 'star': '', 'charge': '', 'skill': []},


];


/*
function createData()
{
    str = '';
    for(let i=1; i<=310; i++)
    {
        mode = '';
        for(var key in mode_list)
        {
            if(mode_list[key].includes(i)) mode = key;
        }
        
        attr = '';
        for(var key in attr_list)
        {
            if(attr_list[key].includes(i)) attr = key;
        }
        
        race = '';
        for(var key in race_list)
        {
            if(race_list[key].includes(i)) race = key;
        }
        
        star = '';
        for(var key in star_list)
        {
            if(star_list[key].includes(i)) star = key;
        }
        
        charge = '';
        for(var key in charge_list)
        {
            if(charge_list[key].includes(i)) charge = key;
        }
        
        skill = '';
        for(var key in skill_list)
        {
            if(skill_list[key].includes(i)) skill += "'"+key+"', ";
        }
        
        str += "{'id': "+i+", 'mode': '"+mode+"', 'attribute': '"+attr+"', 'race': '"+race+"', 'star': '"+star+"', 'charge': '"+charge+"', 'skill': ["+skill+"]},\n"
    }
    console.log(str);
}
*/